Add detection of Huawei Nova 5T
8thwall/ua-parser-js pull request #7
Opened 2020-03-06 18:24 UTC by atomarch

2020-03-06 18:26 UTC, atomarch commented
Model numbers for this device obtained from:
- https://www.gsmarena.com/huawei_nova_5t-9803.php
- https://www.devicespecifications.com/en/model/8b9f5144

Proposed regex validated at:
- https://regex101.com/r/Puyt5H/2

2020-03-09 16:59 UTC, mralbean requested changes
Let's add proper test cases for this to ensure it will get merged into the main ua parser repo.

2020-03-09 18:33 UTC, atomarch commented
good catch - just updated device-test.json

2020-03-09 19:46 UTC, mralbean approved these changes

2020-03-09 19:48 UTC, merged